### ISSUE TITLE
Update to 1.20/1.20.1

### ISSUE THREAD

**Issue by KadTheHunter** [InLieuOfLuna/elytra-recast#8]
Would be great if the mod could support 1.20/1.20.1 :)

**Comment by Rozbiynk** [comment]
bump

**Comment by KadTheHunter** [comment]
@Rozbiynk I actually updated it myself, and made a release [on my fork](https://github.com/KadTheHunter/elytra-recast/releases/tag/2.2.2).

Thought I opened a PR here, guess not. Will do that now.

**Comment by InLieuOfLuna** [comment]
Sorry for the late response, largely not been doing much modding.

Thanks for updating it @KadTheHunter , obviously theres no logic changes, but will run some tests tomorrow before merging just to double check, but looks good to me.

**Comment by Rozbiynk** [comment]
thank you a lot!

**Comment by Rozbiynk** [comment]
incompatible with quilt, it requires outdated version of flk
![изображение](https://github.com/InLieuOfLuna/elytra-recast/assets/95433246/94a6e3a2-8466-49ac-b3de-4381baf1a383)
![изображение](https://github.com/InLieuOfLuna/elytra-recast/assets/95433246/34228ecf-eed3-4d4c-a00c-0ae49ef71102)

**Comment by KadTheHunter** [comment]
@Rozbiynk I'm able to load it on quilt just fine. I think you may have v1.9.4 or older of FLK; If you read the error, it says "requires 1.9.5 _or any newer version_".

I tested the mod with both 1.9.5 and 1.9.6 of FLK on Quilt and it works fine.

Bumped to 1.9.6 in the PR regardless.

**Comment by InLieuOfLuna** [comment]
Seemed to work fine for me,  I didn't have any issues loading up with the newest version of FLK, I'll be updating the mod on modrinth, could you let me know if this is still happening after? I'll probably rewrite this shortly so you don't need either the dependencies.

**Comment by Rozbiynk** [comment]
oh, yea, im only now notice that qkl have only 1.9.4 version of flk( 
![изображение](https://github.com/InLieuOfLuna/elytra-recast/assets/95433246/31f947a6-c9cc-478a-8dce-4a2455c4f59f)

**Comment by Rozbiynk** [comment]
![изображение](https://github.com/InLieuOfLuna/elytra-recast/assets/95433246/d46e4ab7-908a-435f-81a7-1e037638301d)
